- id: mousebot
  type: macOS
  name: 
    fr: MouseBot
    en: MouseBot
  pageCode:
    fr: mousebot
    en: mousebot
  slogan:
    fr: Automatisez votre pointeur!
    en: Automate your mouse!
  shortDescription:
    fr: Un outil pour piloter votre souris à la voix ou au clavier.
    en: A small utility to drive your mouse with voice or keyboard.
  icon:
    small:   /images/apps/icon-mousebot_150px.png
    default: /images/apps/icon-mousebot.svg
  youtube:
    intro: 
        en: rkuo5OiQu84
        fr: rkuo5OiQu84

- id: chapter-splitter
  type: macOS
  name: 
    fr: Chapter Splitter
    en: Chapter Splitter
  pageCode:
    fr: chapter-splitter
    en: chapter-splitter
  slogan:
    fr: Votre découpeuse de film. Un chapitre, une vidéo.
    en: Your movie slicer. One chapter, one video.
  shortDescription:
    fr: Exporter rapidement les chapitre d'un film en autant de vidéos.
    en: Quick export of a movie chapter in as many video files.
  icon:
    small: /images/apps/icon-chapter-splitter_150px.png
    default: /images/apps/icon-chapter-splitter.svg
  shop:
    mac_app_store: https://itunes.apple.com/us/app/video-chapter-splitter/id1341668646?l=fr&ls=1&mt=12
  youtube:
    intro: 
        en: S-_iBP-yjJg
        fr: S-_iBP-yjJg

- id: mygroups
  type: iOS
  name: 
    fr: mes Groupes
    en: my Group Manager
  pageCode:
    fr: mygroups
    en: mygroups
  slogan:
    fr: Vos contacts. Vos groupes. À votre façon.
    en: Your contacts. Your groups. Your way.
  shortDescription:
    fr: Gérez enfin vos groupes de contacts directement à partir de votre 
        iPhone et votre iPad, sans dépendre de votre Mac.
    en: Finally manage your groups of contacts from your iPhone and iPad devices
        without depending on your Mac.
  icon:
    small: /images/apps/icon-mygroups_150px.png
    default: /images/apps/icon-mygroups.svg
  shop:
    app_store: https://itunes.apple.com/app/apple-store/id1471822418?pt=476347&ct=ownweb&mt=8
  frontPage: yes

- id: vatcalc
  type: iOS
  name: 
    fr: Calculette TVA
    en: VAT Calculator
  pageCode:
    fr: calc-tva
    en: vat-calc
  slogan:
    fr: La TVA facile, du bout des doigts.
    en: VAT rate under your fingers tip.
  shortDescription:
    fr: Calculez rapidement un montant hors-taxes ou TTC pour plus de 50 pays.
    en: Quick and efficient computation of VAT amounts for more than 50 countries.
  icon:
    small: /images/apps/icon-calculette-TVA_150px.png
    default: /images/apps/icon-calculette-TVA.svg
  shop:
    app_store: https://itunes.apple.com/app/apple-store/id425126917?pt=476347&ct=ownweb&mt=8
  youtube:
    intro: 
        en: _6pTfm-ashY
        fr: jn1jY7RykVc
  frontPage: yes
  

- id: scrumcards
  type: iOS
  name: 
    fr: Cartes SCRUM
    en: SCRUM Cards
  pageCode:
    fr: cartes-scrum
    en: scrum-cards
  shortDescription:
    fr: Ayez toujours votre jeu de cartes SCRUM toujours dans la poche.
    en: Get your SCRUM cards always in your pocket.
  icon:
    small: /images/apps/icon-SCRUM-cards_150px.png
    default: /images/apps/icon-SCRUM-cards.svg
  shop:
    app_store: http://itunes.apple.com/us/app/cartes-scrum/id436760091?mt=8
  youtube:
    intro:
        en: -anKt0mJ_Vo
        fr: C2xU9gu-Gj4
  frontPage: yes


- id: instantsizing
  type: iOS
  name: 
    fr: Sizing Instantané 
    en: Instant Sizing
  pageCode: instant-sizing
  shortDescription:
    fr: Participez aux réunions de sizing avec des cartes virtuelles.
    en: Virtual cards to participate in sizing meetings.
  icon:
    small: /images/apps/icon-instantSizing_150px.png
    default: /images/apps/icon-instantSizing.svg
  shop:
    app_store: https://itunes.apple.com/us/app/instant-sizing-for-scrum/id1245353972?l=fr&ls=1&mt=8

- id: memetrics
  type: iOS
  name: 
    fr: me-Metrics
    en: me-Metrics
  pageCode: me-metrics
  shortDescription:
    fr: Comptez ce que vous voulez, où vous voulez.
    en: Count what you want, where you want.
  icon:
    small: /images/apps/icon-meMetrics_150px.png
    default: /images/apps/icon-meMetrics.svg
  shop:
    app_store: https://itunes.apple.com/us/app/me-metrics/id982837103?l=fr&ls=1&mt=8
  youtube:
    intro: mmD8QfJ6jH8
    demo: 
        - 6vExXADbyQ8
        - 16ardaE42Lg
        - D6QZ-m6DCJI
        - idKluIVLeSY
        