- id: vatcalc
  name: 
    fr: Calculette TVA
    en: VAT Calculator
  pageCode:
    fr: calc-tva
    en: vat-calc
  slogan:
    fr: La TVA facile, du bout des doigts.
    en: VAT rate under your fingers tip.
  shortDescription:
    fr: Calculez rapidement un montant hors-taxes ou TTC pour plus de 50 pays.
    en: Quick and efficient computation of VAT amounts for more than 50 countries.
  icon:
    small: /images/apps/icon-calculette-TVA_150px.png
    default: /images/apps/icon-calculette-TVA.svg
  shop:
    app_store: https://itunes.apple.com/app/apple-store/id425126917?pt=476347&ct=ownweb&mt=8
  youtube:
    intro: 
        en: _6pTfm-ashY
        fr: jn1jY7RykVc
  

- id: scrumcards
  name: 
    fr: Cartes SCRUM
    en: SCRUM Cards
  pageCode:
    fr: cartes-scrum
    en: scrum-cards
  shortDescription:
    fr: Ayez toujours votre jeu de cartes SCRUM toujours dans la poche.
    en: Get your SCRUM cards always in your pocket.
  icon:
    small: /images/apps/icon-SCRUM-cards_150px.png
  shop:
    app_store: http://itunes.apple.com/us/app/cartes-scrum/id436760091?mt=8
  youtube:
    intro:
        en: -anKt0mJ_Vo
        fr: C2xU9gu-Gj4


- id: memetrics
  name: 
    fr: me-Metrics
    en: me-Metrics
  pageCode: me-metrics
  shortDescription:
    fr: Comptez ce que vous voulez, où vous voulez.
    en: Count what you want, where you want.
  icon:
    small: /images/apps/icon-meMetrics_150px.png
  shop:
    app_store: https://itunes.apple.com/us/app/me-metrics/id982837103?l=fr&ls=1&mt=8
  youtube:
    intro: mmD8QfJ6jH8
    demo: 
        - 6vExXADbyQ8
        - 16ardaE42Lg
        - D6QZ-m6DCJI
        - idKluIVLeSY
        

